FROM eclipse-temurin:21-jdk-jammy

LABEL maintainer="bank.com"

COPY build/libs/eurekaserver-0.0.1-SNAPSHOT.jar eurekaserver-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "eurekaserver-0.0.1-SNAPSHOT.jar"]